service:
  name: openline-orders
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  stage: ${opt:stage, self:provider.stage}
  ordersTableName: openline-orders-${self:custom.stage}
  phonesTableName: openline-phones-${self:custom.stage}
  # callsTableName: openline-calls-${self:custom.stage}
  domains:
    prod: api.openline.telspark.com
    staging: api-staging.openline.telspark.com
    dev: api-dev.openline.telspark.com
  customDomain:
    domainName: ${self:custom.domains.${self:custom.stage}}
    basePath: 'orders'
    certificateName: '*.openline.telspark.com'
    stage: "${self:custom.stage}"
    createRoute53Record: true
  cors:
    prod: 'https://openline.telspark.com'
    dev: '*'
  phoneSnsTopic: "openline-phones-${self:custom.stage}-sns-phone"
  phoneSnsTopicArn:
    local:
      "arn:aws:sns:us-east-1:123456789012:${self:custom.phoneSnsTopic}"
    dev:
      { "Fn::Join" : ["", ["arn:aws:sns:${self:provider.region}:", { "Ref" : "AWS::AccountId" }, ":${self:custom.phoneSnsTopic}" ] ]  }
    prod:
     { "Fn::Join" : ["", ["arn:aws:sns:${self:provider.region}:", { "Ref" : "AWS::AccountId" }, ":${self:custom.phoneSnsTopic}" ] ]  }
  connectionSnsTopic: "openline-connections-${self:custom.stage}-sns-connection"
  connectionSnsTopicArn:
    # local:
    #   "arn:aws:sns:us-east-1:123456789012:${self:custom.phoneSnsTopic}"
    dev:
      { "Fn::Join" : ["", ["arn:aws:sns:${self:provider.region}:", { "Ref" : "AWS::AccountId" }, ":${self:custom.connectionSnsTopic}" ] ]  }
    prod:
     { "Fn::Join" : ["", ["arn:aws:sns:${self:provider.region}:", { "Ref" : "AWS::AccountId" }, ":${self:custom.connectionSnsTopic}" ] ]  }

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-domain-manager

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    ORDERS_TABLE: ${self:custom.ordersTableName}
    PHONES_TABLE: ${self:custom.phonesTableName}
    CORS: ${self:custom.cors.${self:custom.stage}}
  iamRoleStatements:
    - Effect: Allow
      Action:
        # - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        # - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:table/openline-orders-${opt:stage, 'dev'}"
    - Effect: Allow
      Action:
        # - dynamodb:Scan
        # - dynamodb:GetItem
        # - dynamodb:PutItem
        # - dynamodb:DeleteItem
        - dynamodb:Query
        - dynamodb:UpdateItem
      Resource: "arn:aws:dynamodb:us-east-1:*:table/openline-phones-${opt:stage, 'dev'}"
    # - Effect: Allow
    #   Action: 
    #     - execute-api:ManageConnections
    #   Resource: "arn:aws:execute-api:us-east-1:463704812673:co3xyaosg9/dev/POST/@connections/{connectionId}"
    - Effect: Allow
      Action:
        - SNS:Publish
      Resource: { "Fn::Join" : ["", ["arn:aws:sns:${self:provider.region}:", { "Ref" : "AWS::AccountId" }, ":${self:custom.phoneSnsTopic}" ] ]  }
    - Effect: Allow
      Action:
        - SNS:Publish
      Resource: { "Fn::Join" : ["", ["arn:aws:sns:${self:provider.region}:", { "Ref" : "AWS::AccountId" }, ":${self:custom.connectionSnsTopic}" ] ]  }


functions:
  createCharge:
    handler: handler.create
    events:
      - http:
          method: post
          path: ''
          cors: true

  fetchCharge:
    handler: handler.fetchCharge
    events:
      - http:
          method: get
          path: '/{orderId}'
          cors: true

  openNodeChargeWebhook:
    handler: handler.openNodeChargeWebhook
    events:
      - http:
          method: post
          path: 'payment'
          cors: true
    environment:
      phoneSnsTopicArn: ${self:custom.phoneSnsTopicArn.${self:provider.stage}}
      connectionSnsTopicArn: ${self:custom.connectionSnsTopicArn.${self:provider.stage}}


resources:
  Resources:
    OpenlineOrdersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.ordersTableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        # Set the capacity to auto-scale
        BillingMode: PAY_PER_REQUEST
        # # add stream to dynamo table
        # StreamSpecification:
        #   StreamViewType: NEW_IMAGE